#!/bin/bash

APP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
APP_USER="$( stat -c '%U' ${APP_DIR} )"
CURRENT_USER=`whoami`

if [ "${CURRENT_USER}" != "${APP_USER}" ]; then
    echo "Warning: Running as ${CURRENT_USER}, app dir owned by ${APP_USER}"
fi

${APP_DIR}/.venv/bin/python ${APP_DIR}/manage.py "$@"
